# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyCode',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.BaseModel')),
                ('currency_name', models.CharField(max_length=128)),
                ('currency_code', models.CharField(max_length=12)),
            ],
            bases=('Client.basemodel',),
        ),
        migrations.CreateModel(
            name='ExpenseProduct',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.BaseModel')),
                ('product_name', models.CharField(max_length=128)),
                ('product_type', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
            bases=('Client.basemodel',),
        ),
        migrations.CreateModel(
            name='ExpensesTracker',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.BaseModel')),
                ('expensed_on', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('amount', models.FloatField(null=True)),
                ('description', models.CharField(max_length=1024)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.CurrencyCode')),
            ],
            bases=('Client.basemodel',),
        ),
        migrations.AddField(
            model_name='expenseproduct',
            name='expensetracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.ExpensesTracker'),
        ),
    ]
